
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import PathnameWrapper from "./components/PathNameWrapper";
import FetchDataStore from "./components/FetchDataStore";
// import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kazy Systems",
  description: "Generated by create next app",
};

// const pathname = usePathname();
// const isAdminRoute = pathname.startsWith("/admin");

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
            <FetchDataStore/>
        <PathnameWrapper>
          {children}
        </PathnameWrapper>
      </body>
    </html>
  );
}
